# Generated by Django 3.2.2 on 2021-05-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update At')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('goals', models.IntegerField(verbose_name='Goals')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update At')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='api.equipo', verbose_name='Equipo')),
            ],
        ),
    ]
